In [1]:
x=5

In [2]:
y="hello"


In [3]:
print(x+y)


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [4]:
Start=1
end = 100
result = D
for i in range(start, end + 1):
if i > 1:
for j in range(z, i):
if (i % j) = 0:
break
else:
result.append(i)
print(result)

IndentationError: expected an indented block after 'for' statement on line 4 (189464131.py, line 5)

In [8]:
import numpy as np
x = np.array([[1, 2], [3,4]])
y = np.array([[5, 6], [7, 81]])
z = np.concatenate((x, y), axis=1)
print(z)

[[ 1  2  5  6]
 [ 3  4  7 81]]


In [9]:
import numpy as np
x = np.array([1, 2, 31)
y = np.array([4, 5, 61)
z = np.hstack((x, y))
print(z)

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (940057605.py, line 2)

In [10]:
import numpy as np
x = np.array([1, 2, 31])
y = np.array([4, 5, 61])
z = np.hstack((x, y))
print(z)

[ 1  2 31  4  5 61]
