In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2], [3,4], [5,6], [7,8]])
arr2 = np.array([[9,10], [11,12], [13,14], [15,16]])


In [3]:
arr = np.hstack((arr1, arr2))

In [4]:
print(arr)

[[ 1  2  9 10]
 [ 3  4 11 12]
 [ 5  6 13 14]
 [ 7  8 15 16]]
